name: docker-build-push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx for Frontend
        uses: docker/setup-buildx-action@v1
        id: frontendBuilder
        
      - name: Set up Docker Buildx for Backend
        uses: docker/setup-buildx-action@v1
        id: backendBuilder

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Frontend/Dockerfile
          builder: ${{ steps.frontendBuilder.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restaurants2030-frontend:latest
      
      - name: Build and push Backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Backend/API/Dockerfile
          builder: ${{ steps.backendBuilder.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restaurants2030-backend:latest
